layout_spectrum: 1
color:
  saturation: 0.8243728
  lightness: 0.6810036
  brandStrength: 0.9390681
  brandColors:
    - '#313139'
    - '#DA9876'
    - '#FFFFFB'
    - '#8E8A89'
    - '#9EB661'
  rhythmicContrast: 0.9462366
typography_spectrum: 0.8548387
name: akeem
