layout_spectrum: 0.6141321
typography_spectrum: 0.3583375
color:
  saturation: 0.3714691
  lightness: 0.07215042
  brandStrength: 0.08172712
  rhythmicContrast: 0.5257539
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
name: akeem
